# Generated by Django 3.2.18 on 2023-06-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgi_currencies', '0002_auto_20230625_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cours'),
        ),
    ]
