# Generated by Django 3.2.18 on 2023-07-09 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgi_currencies', '0005_auto_20230709_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='propagation',
            field=models.TextField(blank=True, verbose_name='propagation'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='pgi_currencies.currency', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='rate'),
        ),
    ]
